### PR TITLE
Create LICENSE

### LINKED ISSUE #2: missing license for the repo
👋 Just found this repo does not have any license, it would be good to add OSI-approved one, https://spdx.org/licenses/

### PR DESCRIPTION
**Pull request by JoeNyland**
Fixes #2

### CODE REVIEW

**Comment by chenrui333** [comment]
@JoeNyland, if you dont strongly insist about GPL-3.0, I actually think these three licenses are better choices:
- Apache-2.0
- MIT
- BSD-3-Clause

**Comment by chenrui333** [comment]
Thanks for adding one. :)

**Comment by JoeNyland** [comment]
@chenrui333 Ok. What are the key reasons why you recommend one of those licenses over GPL-3.0? I'm not very well informed on licenses, but I did do some research before I chose GPL-3.0 and I still feel a bit lost, so I'm keen to hear other people's input on what licenses are recommended.

**Comment by chenrui333** [comment]
GPL-3.0 is strong copyleft license, meaning everything inherit your work would need to follow GPL license, it is just not quite permissive and business friendly to help your work adopted. but you can go either way though. :)

This is a good diagram in general, https://en.wikipedia.org/wiki/File:Quick-guide-gplv3-compatibility.svg
Full wiki on this theme, https://en.wikipedia.org/wiki/GNU_General_Public_License

**Comment by JoeNyland** [comment]
@chenrui333 Thanks for taking the time to explain and for the links. I'll try to educate myself a bit better on licenses.

**Comment by JoeNyland** [comment]
Following on from the above discussion, I've updated the license to MIT in #4

**Comment by chenrui333** [comment]
Thanks @JoeNyland!!

**Comment by chenrui333** [comment]
If possible, do you mind adding a new release, then the LICENSE file would be included in the new source code distribution. Much appreciated!

**Comment by JoeNyland** [comment]
@chenrui333 I've just created a new release now 🙂  https://github.com/JoeNyland/rake-completion/releases/tag/v1.0.1

**Comment by chenrui333** [comment]
Thanks!

**Pull request merged**
